export const DishType = [
  "Biscuits and cookies",
  "Bread",
  "Cereals",
  "Condiments and Sauces",
  "Drinks",
  "Desserts",
  "Egg",
  "Main course",
  "Omelet",
  "Pancake",
  "Preps",
  "Preserve",
  "Salad",
  "Sandwiches",
  "Soup",
  "Starter",
];

export const MealType = [
  "Breakfast",
  "Brunch",
  "Lunch",
  "Dinner",
  "Snack",
  "Teatime",
];

export const CuisineType = [
  "American",
  "Asian",
  "British",
  "Caribbean",
  "Central europe",
  "Chinese",
  "Eastern europe",
  "French",
  "Greek",
  "Indian",
  "Italian",
  "Japanese",
  "Korean",
  "Kosher",
  "Mediterranean",
  "Mexican",
  "Middle eastern",
  "Nordic",
  "South american",
  "South east asian",
  "World",
];

export const HealthType = [
  "Alcohol-Cocktail",
  "Alcohol-Free",
  "Celery-Free",
  "Crustcean-Free",
  "Dairy-Free",
  "DASH",
  "Egg-Free",
  "Fish-Free",
  "FODMAP-Free",
  "Gluten-Free",
  "Immuno-Supportive",
  "Kidney-Friendly",
  "Kosher",
  "Low Potassium",
  "Low Sugar",
  "Lupine-Free",
  "Mediterranean",
  "Mollusk-Free",
  "Mustard-Free",
  "No oil added",
  "Paleo",
  "Peanut-Free",
  "Pescatarian",
  "Red-Meat-Free",
  "Sesame-Free",
  "Shellfish-Free",
  "Soy-Free",
  "Sugar-Conscious",
  "Sulfite-Free",
  "Tree-Nut-Free",
  "Vegan",
  "Vegetarian",
  "Wheat-Free",
];

export const DietType = [
  "Balanced",
  "High-Fiber",
  "High-Protein",
  "Low-Carb",
  "Low-Fat",
  "Low-Sodium",
];
